### ISSUE TITLE
QAVAJS process freezes on deeply equal expect

### ISSUE THREAD

**Issue by ALegchilov** [qavajs/steps-memory#21]
![image](https://github.com/qavajs/steps-memory/assets/46843062/7348780c-3880-42bb-879e-03a3f5e24b04)
There are two json files. The only difference is one of files have been prettified. Deep equal validation of this files leads to hanging off.
https://epam-my.sharepoint.com/:u:/p/alexandr_legchilov/EUU8gFHLWMhOowbGN_EFJ4YB9nrGLFsKli6rnG0zBSp6yg?e=xUJULz
https://epam-my.sharepoint.com/:u:/p/alexandr_legchilov/EWlrjRH5LU5LjMC8F_i65cIBY6z4OhUpdKZx2DNtMHlkdA?e=ocFP07

**Comment by AlexGalichenko** [comment]
@ALegchilov, in this example files are stored to memory as buffers, seems like this is the rootcause. Try to parse it as json before validation.
